#!/usr/bin/env python3
"""Local prompt-boundary regression runner; never downloads dependencies or calls a model.

Default mode uses normal project imports. --dependency-isolated explicitly substitutes only
the unavailable config/schema/SDK import boundaries; it does NOT replace generate.py or
seeds.py, and does NOT count real-config validation as run. Both modes use fake inference.
"""
import argparse
from contextlib import ExitStack
from datetime import datetime, timezone
import hashlib
import importlib.util
import io
import json
from pathlib import Path
import socket
import subprocess
import sys
from types import ModuleType
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tests"))


def import_only_stubs():
    # No fake model output is generated by these placeholders. Tests explicitly patch Teacher.
    for leaf, symbol in (("config", "Config"), ("schemas", "GeneratedQuestion"), ("teacher", "Teacher")):
        mod = ModuleType(f"distillkit.{leaf}")

        class UnavailableDependency:
            def __init__(self, *args, **kwargs):
                raise AssertionError("Import-only dependency placeholder must not be instantiated")

        setattr(mod, symbol, UnavailableDependency)
        sys.modules[mod.__name__] = mod


def load_baseline(path):
    spec = importlib.util.spec_from_file_location("distillkit._unmodified_generate", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def before_after(test_module, baseline_path):
    """Run the unchanged old entry point and the fixed entry point on identical synthetic inputs."""
    old = load_baseline(baseline_path)
    rows = []
    for name, mode in (("prose", "prose"), ("tool_trace", "call")):
        fixture = test_module.GoldProvenanceTests()
        fixture.setUp()
        try:
            fixture.inject_heldout(name)
            fixture.cfg.generate.tool_fraction = 0 if mode == "prose" else 1
            fixture.cfg.generate.tool_mix = {"call": 1}
            with test_module.isolated_path(old):
                old.run(fixture.cfg)
            requests = test_module.FakeTeacher.instances[0].requests
            leaked = [r for r in requests if test_module.MARKER in json.dumps(r)]
            assert leaked and all(r["kind"] == "answer" for r in leaked)
            fixture.assert_blocked("resolves to eval")
            rows.append({"path": name, "status": "passed", "old_teacher_requests": len(requests),
                         "old_answer_requests_containing_unique_heldout_marker": len(leaked),
                         "old_question_requests_containing_marker": 0,
                         "fixed_teacher_constructions": 0, "fixed_teacher_requests": 0,
                         "baseline_sha256": hashlib.sha256(baseline_path.read_bytes()).hexdigest()})
        finally:
            fixture.doCleanups()
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dependency-isolated", action="store_true")
    parser.add_argument("--baseline", type=Path)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    dependencies = ("yaml", "pydantic", "dotenv", "openai", "tenacity")
    missing = [name for name in dependencies if importlib.util.find_spec(name) is None]
    report = {"recorded_at_utc": datetime.now(timezone.utc).isoformat(), "python": sys.version,
              "python_executable": sys.executable, "missing_dependencies": missing,
              "execution_mode": "dependency-isolated mock integration" if args.dependency_isolated else "normal-dependency mock integration",
              "real_model_runs": 0, "network_requests": 0, "generated_training_files": 0,
              "status": "not_run", "passed": 0, "failed": 0, "errors": 0, "skipped": 0,
              "not_run": [], "before_after_regressions": []}
    if not args.dependency_isolated and missing:
        report["not_run"] = [{"scope": "normal-dependency integration suite",
                              "reason": "Missing local project dependencies: " + ", ".join(missing)}]
        args.report.write_text(json.dumps(report, indent=2) + "\n")
        print(json.dumps({k: report[k] for k in ("status", "execution_mode", "missing_dependencies", "not_run")}, indent=2))
        return 2
    if args.dependency_isolated:
        import_only_stubs()
        report["not_run"] = [{"test": "ConfiguredGoldTests.test_actual_configured_paths_build_expected_prompts",
                              "reason": "Real YAML/Config/SDK imports unavailable: " + ", ".join(missing)},
                             {"test": "ConfiguredGoldTests.test_actual_configs_preserve_eval_docs_exclusion",
                              "reason": "Real YAML/Config validation unavailable: " + ", ".join(missing)}]

    def forbidden(*args, **kwargs):
        raise AssertionError("Network/process execution is forbidden in these tests")

    with ExitStack() as stack:
        stack.enter_context(patch.object(socket.socket, "connect", forbidden))
        stack.enter_context(patch.object(socket, "create_connection", forbidden))
        stack.enter_context(patch.object(subprocess, "Popen", forbidden))
        import test_gold_provenance as tests
        suite = unittest.defaultTestLoader.loadTestsFromTestCase(tests.GoldProvenanceTests)
        if not args.dependency_isolated:
            suite.addTests(unittest.defaultTestLoader.loadTestsFromTestCase(tests.ConfiguredGoldTests))
        log = io.StringIO()
        result = unittest.TextTestRunner(stream=log, verbosity=2).run(suite)
        report.update({"status": "passed" if result.wasSuccessful() else "failed",
                       "tests_run": result.testsRun,
                       "passed": result.testsRun - len(result.failures) - len(result.errors) - len(result.skipped),
                       "failed": len(result.failures), "errors": len(result.errors), "skipped": len(result.skipped),
                       "test_log": log.getvalue(),
                       "scope": "Actual generate.run, _gold, question_jobs, _mode_rule, tool_trace, to_api and seed loading. Fake teacher, in-memory appenders and a synthetic tool adapter; no actual model or tool implementation.",
                       "unverified": ["Real YAML/Pydantic configuration and response validation in isolated mode",
                                      "Real Teacher/OpenAI request serialization and model behavior",
                                      "Actual file append/resume IO (MemoryAppender used)",
                                      "Source provenance truth and all semantic leakage"]})
        if args.baseline and result.wasSuccessful():
            report["before_after_regressions"] = before_after(tests, args.baseline)
    args.report.write_text(json.dumps(report, indent=2) + "\n")
    print(log.getvalue())
    print(json.dumps({k: report[k] for k in ("execution_mode", "passed", "failed", "errors", "skipped", "not_run", "before_after_regressions")}, indent=2))
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
