"""Opt-in source-family admission for training. This is not a semantic leakage detector."""
import hashlib
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class _Entry(BaseModel):
    model_config = ConfigDict(extra='forbid')


class Family(_Entry):
    split: Literal['train', 'development', 'final', 'quarantine']
    parents: list[str]
    lineage_reviewed: bool


class Document(_Entry):
    doc_id: str = Field(min_length=1)
    path: str = Field(min_length=1)
    sha256: str = Field(pattern=r'^[0-9a-f]{64}$')
    family: str = Field(min_length=1)
    approved_for_training: bool
    origin: str = Field(min_length=1)
    source_version: str = Field(min_length=1)
    permission_evidence: str = Field(min_length=1)
    admission_review_sha256: str = Field(pattern=r'^[0-9a-f]{64}$')


class Registry(_Entry):
    version: Literal['source-family-registry-v1']
    families: dict[str, Family]
    documents: list[Document]


def admitted_sources(cfg):
    """Validate actual selected files, hashes and transitive family splits.

    None preserves legacy behavior. New campaigns must opt in explicitly. The
    registry is a reviewed configuration input, never text generated by a teacher.
    Licensing/semantic review is recorded by the caller; hashes do not prove it.
    """
    path = getattr(cfg.seeds, 'registry', None)
    if path is None:
        return None
    path = Path(path)
    raw = path.read_bytes()
    registry = Registry.model_validate_json(raw)
    docs = {d.doc_id:d for d in registry.documents}
    if len(docs) != len(registry.documents):
        raise ValueError('source registry has duplicate document IDs')
    if len({d.path for d in registry.documents}) != len(registry.documents):
        raise ValueError('source registry has duplicate source paths')
    root = cfg.seeds.dir.resolve()

    def ancestors(name, stack=(), require_train=True):
        if name in stack:
            raise ValueError(f'source family cycle: {stack + (name,)}')
        if name not in registry.families:
            raise ValueError(f'unknown source family or ancestor {name!r}')
        f = registry.families[name]
        if not f.lineage_reviewed:
            raise ValueError(f'unresolved source-family lineage for {name!r}')
        if require_train and f.split != 'train':
            raise ValueError(f'source family {name!r} resolves to {f.split}; training requires train')
        result = {name}
        for parent in f.parents:
            result.update(ancestors(parent, (*stack,name), require_train))
        return result

    # Explicit eval_docs is split evidence even when a registry incorrectly calls
    # its family train. Aliases/descendants cannot bypass the existing holdout.
    held_documents = [d for d in registry.documents if d.doc_id in cfg.seeds.eval_docs]
    held_families = set()
    for name, family in registry.families.items():
        if family.split in ('development', 'final'):
            held_families.update(ancestors(name, require_train=False))
    for d in held_documents:
        held_families.update(ancestors(d.family, require_train=False))
    held_hashes = {d.sha256 for d in registry.documents
                   if d in held_documents or d.family in held_families}
    selected = {}
    for source in sorted(cfg.seeds.dir.glob('*.md')):
        doc_id = source.stem
        if doc_id not in docs:
            raise ValueError(f'unlisted selected source {doc_id!r}: {source}')
        d = docs[doc_id]
        relative = Path(d.path)
        if relative.is_absolute() or '..' in relative.parts or (root/relative).resolve() != source.resolve() or not source.resolve().is_relative_to(root):
            raise ValueError(f'source registry path mismatch or escape for {doc_id!r}')
        if hashlib.sha256(source.read_bytes()).hexdigest() != d.sha256:
            raise ValueError(f'source registry hash mismatch for {doc_id!r}')
        if doc_id in cfg.seeds.eval_docs:
            continue  # Existing explicit holdout exclusion remains additional protection.
        if not d.approved_for_training:
            raise ValueError(f'source {doc_id!r} lacks reviewed training admission')
        lineage = ancestors(d.family)
        if lineage & held_families:
            raise ValueError(f'source {doc_id!r} shares held-out or explicit eval_docs family ancestry: {sorted(lineage & held_families)}')
        if d.sha256 in held_hashes:
            raise ValueError(f'source {doc_id!r} exactly copies an explicit eval_docs source')
        selected[doc_id] = {'source_family':d.family, 'source_families':sorted(lineage),
                           'document_sha256':d.sha256,
                           'source_registry_sha256':hashlib.sha256(raw).hexdigest()}
    return selected


def record_source_binding(cfg, row):
    """Fail closed on stale registry metadata before using a record as training evidence."""
    selected = admitted_sources(cfg)
    if selected is None:
        return
    doc_id = row.get('doc_id')
    if doc_id not in selected:
        raise ValueError(f'record source {doc_id!r} is not an admitted training source')
    for field, value in selected[doc_id].items():
        if row.get(field) != value:
            raise ValueError(f'record {row.get("id")!r} has missing or stale {field}')
